### ISSUE TITLE
Optimize the Document.SaveChanges()

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/Marten#10]
Maybe use data adapters in ADO.Net to submit all the changes in one batch? May not be *that* crazy. Another alternative would be to submit a batch of JSON and have a plv8 sproc in the database do the work of pushing the data to the right places.

**Comment by nickvane** [comment]
For data adapters to work for batching, npgsql needs to support batch size (https://msdn.microsoft.com/en-us/library/aadf8fk2%28v=vs.110%29.aspx), and I think it doesn't. Looking at the code base: https://github.com/npgsql/npgsql/search?utf8=%E2%9C%93&q=UpdateBatchSize&type=Code and searching online yields no results. The only batch thing that comes close is http://www.npgsql.org/doc/copy.html, but that does only insert, no update or delete.
Alternatives are either like you suggested having a sproc deal with the changes, or append statements as a single command (mweh, because you might lose granularity on statement feedback).

**Comment by jeremydmiller** [comment]
@nickvane I figured that sooner or later we'd hit some kind of limitation on the postgres client. I'm going to try to get some kind of non-trivial test database (we're thinking about using Octokit to get at Github data) together before I try to tackle this so we can get some non-imaginary numbers.

The ON CONFLICT idea sounds like something worth trying to me. I appreciate the tip.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/Marten/commit/dc873e63e36242ae113f09660452a0176287e860. The new UnitOfWork and UpdateBatch classes use a single command to make all the changes.
