### ISSUE TITLE
Sharding support

### ISSUE THREAD

**Issue by jeffdoolittle** [JasperFx/marten#104]
Blind/HiLo sharding - https://ayende.com/blog/155297/ravendb-sharding-blind-sharding
Data Driven sharding - https://ayende.com/blog/155329/ravendb-sharding-data-driven-sharding

**Comment by jeremydmiller** [comment]
@jeffdoolittle Can you elaborate on that? What are you envisioning?

**Comment by jeffdoolittle** [comment]
I was curious to see what others might be thinking along such lines. I know Raven DB has sharding capabilities like this. Would be nice to spin up some AWS Postgres instances and have the ability to both persist and query across sharded instances. Also would be nice to configure sharing using the strategies I mentioned in the original description on this issue.

Anyone else have feedback/ideas on the utility, feasibility, and/or demand for such a feature?

--Jeff

**Comment by jeffdoolittle** [comment]
more info:

https://ravendb.net/docs/article-page/3.0/csharp/server/scaling-out/sharding/how-to-setup-sharding
https://ayende.com/blog/170881/ravendb-sharding-enabling-shards-for-existing-database
http://stackoverflow.com/questions/6013911/ravendb-planning-for-scalability

**Comment by maggiepint** [comment]
I'd be interested to know where you guys want to go with this.

As a casual observer, I'll note that I would use a shard strategy similar to RavenDBs. This was something I  really liked about RavenDB, - the shard implementation is quite clean. I don't see the need for blind sharding though. IMO If you're going to shard, you might as well define where your data is going.

It's worth nothing that I kinda like the similar thing Microsoft did with Elastic Database tools on Azure for multi-shard data routing and querying. In particular, the practice of pulling a shard map into the client, and then having multiple ways to open database connections based on that shard map makes sense to me. I haven't used that in production though.

**Comment by jeremydmiller** [comment]
I honestly haven't done more on this than browse the links @jeffdoolittle put up above. My thought for us at work was to just use something like [Citrus](https://www.citusdata.com/solutions/infrastructure/scaling-out-postgresql).

**Comment by jeffdoolittle** [comment]
Well goodness, Citus looks pretty awesome.

**Comment by tim-cools** [comment]
Wow, indeed! 

:+1: for not making this a Marten responsibility

**Comment by khalidabuhakmeh** [comment]
I would agree that leaning on the tooling and ecosystem Postgres provides should be the first option to solving any problem with management.

**Comment by jeremydmiller** [comment]
I'm shutting this one down. At least until someone can prove that Citrus or pg_shard isn't enough.

**Comment by pruiz** [comment]
Hi @jeremydmiller  well, to be honest, citus does have some limitations (including cros-shard ACID), etc. which are in fact an issue.

Also, sharding by using an specific product (like citus) which does provide distributed-postgres, does provide some advantages, but it has limited performance scalability compared to sharding  by means of completelly-isolated postgres instances.

I think we still need some kind of mininal support from marten by which we could provide some sort of ShardingStrategy in order to support the later case (ie. distribute entries among different [and indepentend] postgres instances). This way, an object will be sharded by their identity key (or by some other column/property, like the object's tenant identifier property).

Just my two cents.

**Comment by jeremydmiller** [comment]
@pruiz K. I'm reopening this then. Might just end up being closely related to the multi-tenancy issue.

**Comment by jaydanielian** [comment]
@jeremydmiller , this library is outstanding. As far as the sharding discussion goes, I would point you to another fabulous library called Sequel, this one is in the Ruby community maintained by Jeremy Evans http://sequel.jeremyevans.net/rdoc/files/doc/sharding_rdoc.html

His library allows for multiple server nodes to be specified in the connection pool, those server nodes can be tagged as read-only (nice for directing select queries to read replicas automatically), or the application allows for database level sharding and its smart enough to round robin queries to the appropriate "node" in the server list. Extensions are also available meaning you can always instruct the session to go to a particular node. 

Anyway, I hope you will see this example and be able to extract some inspiration in terms of applying this concept to Marten. Using Ruby Sequel, I am able to application shard the data across several Amazon Aurora instances thus getting horizontal scalability and nice automatic HA in the event of data/instance. Its a pretty powerful feature for the data driver to include.

**Comment by jeremydmiller** [comment]
This one might be much more viable *after* we get the multi-tenancy support going.

**Comment by nkosi23** [comment]
@jeremydmiller it looks like multi-tenancy support is present now, is this ticket in a position to be reopened?

**Comment by jeremydmiller** [comment]
@nkosi23 It probably should never have been closed, and the multi-tenancy I referred to was in regards to the "conjoined" multi-tenancy model we've had since Marten 2.0. The sharding would be based on built in Postgresql sharding rather than any kind of external library trickery with connection strings. The difficulty here is actually with migrating to a sharded model because you have to essentially blow away the original table and replace it with shards. That work hasn't been done yet.

Honestly, after the big v5 push, I'm probably opting for a significant break on big Marten work for a bit.
