### ISSUE TITLE
LINQ: Support for 'IN (?, ?, ?, ?)' in Where clause

### ISSUE THREAD

**Issue by leypascua** [JasperFx/marten#1086]
I need to write a LINQ query that will convert into: 
`SELECT * FROM [table] WHERE field IN (?, ?, ?)`

Currently the code below is throwing a NotSupportedException:

```
var externalCodes = new string[] { "one", "two", "three" };
var query = db
   .Query<TerritoryData>()
   .Where(td => td.TerritoryType == territoryType);

if (externalCodes.Any())
{
   query = query.Where(td => externalCodes.Contains(td.ExternalCode));
}

// throws a NotSupportedException
return query.ToList();
```
Is there any workaround for this?

**Comment by mysticmind** [comment]
@leypascua you can try to use `IsOneOf`, check http://jasperfx.github.io/marten/documentation/documents/querying/linq/#sec19

**Comment by leypascua** [comment]
Thanks, @mysticmind.

Unfortunately I cannot use extension methods in the Marten assembly in our use-case because Marten is not referenced in the assembly where the code resides. We decided to put ISession behind an interface in the event that we may need to swap Marten with a more widely-adpoted document database.

**Comment by ericgreenmix** [comment]
@leypascua I believe this is supported on `List` but not on an array.

Try using the following with your query.
```
var externalCodes = new List<string> { "one", "two", "three" };
```

**Comment by jeremydmiller** [comment]
@leypascua "We decided to put ISession behind an interface in the event that we may need to swap Marten out with a more widely-adpoted document database."

Let me translate that to "we decided to make Marten almost unusable and eliminate any usage of the advanced features that we could use to make our application more performant on the off chance we decide to switch technologies later to something that works like our abstraction".  

Seriously, these kinds of low level abstractions that wrap right around something like Marten's `IDocumentSession` are so harmful in your application. 

But P.S., you could get into Marten itself and pull the IsOneOf implementation into whatever assembly you have that does the wrapping because it's done through Marten's Linq extensibility mechanisms. See http://jasperfx.github.io/marten/documentation/documents/advanced/customizing_linq/.

I'm closing this one as "not going to fix"
