### ISSUE TITLE
Support for soft delete properties on returned objects

### ISSUE THREAD

**Issue by Leh2** [JasperFx/marten#1346]
When using soft deletion and querying with `MaybeDeleted()` i'm missing the possibility to add the deleted info to my object/document,. This makes it possible to tell which of my fetched documents is deleted. 

I tried adding the following properties, but with no luck:

``` csharp
public bool IsDeleted { get; set; }
public bool Deleted { get; set; }
public DateTime DeletedAt { get; set; }
```

The needed functionality is available for version and optimistic concurrent with `.VersionedWith(x => x.Version)`

**Comment by Leh2** [comment]
@oskardudycz here u go

**Comment by mysticmind** [comment]
I think it would help to look including `DocumentMetadata` for each of the documents so that it will be more useful with the following properties:
- LastModified
- CurrentVersion
- DotNetType
- DocumentType
- Deleted
- DeletedAt
- TenantId

**Comment by barryhagan** [comment]
This was a sore spot for me, so I want to add my observations.    As it stands today, it was better to handle this in my own model/code.  Make the deleted properties first class on your objects and do what is necessary during read and write based on your needs.  Otherwise you have to make `MetadataFor` calls to get this information, and there is no way to do that for a collection of objects.   

I would want to see `MetadataForMany<T>` if things proceed that way.   What would be nice is if this metadata was automatically cached in session when docs are read from the db so there wasn't another roundtrip (maybe tied to the IIdentityMap), but that is a bigger change.

Also, `Load<T>` and `LoadMany<T>` do not have soft deleted support so you must make the MetadataFor queries there for what is imho, a critical path:   The user has a known id, it is unlikely that they should see deleted docs, so now I must make two roundtrips to check if the doc is deleted.

**Comment by Leh2** [comment]
I like the solution made for version with `[MyClass].VersionedWith(x => x.[VersionProperty])`, so you decide which meta properties you like to be first class. 

With this solution you avoid extra round trips for meta data and avoid the merging of the two lists afterwards. And you can easily make the delete check after using `Load<T>`.

**Comment by mysticmind** [comment]
@Leh2 agree that the implementation done for `VersionedWith` is quite elegant to replicate and use for other meta data properties.

**Comment by barryhagan** [comment]
I agree it is really the only way to make soft deletes truly usable by calling code.  When implemented, this could also provide undelete/restore support, which is another gap in the current feature. Mutations to these soft delete metadata fields would need to be dealt with one way or another on save to keep the database consistent and it seems wrong to ignore a client that set Deleted=false and tried to save changes.

**Comment by oskardudycz** [comment]
`VersionedWith` seems to be a good idea for me. That seems to be the cleanest solution. Although I need to get more familiar to that to understand the potential complexity.

**Comment by Miggleness** [comment]
To summarize, 

Preferred solution: Apply similar solution as .VersionedWith(). 

Api can be .MarkDeletedWith()

Other considerations: Marten shouldnt ignore documents whose delete flag is true and registered thru the MarkedDeletedWith() api. Need to dig deeper with this one

**Comment by barryhagan** [comment]
I've got a prototype of this feature started in my fork if you want to take a look at the direction.
https://github.com/barryhagan/marten/commits/issue_1346

This will treat metadata mapped fields as read-only, and will throw if the client attempts to change them in a session.  Trying to make the properties write-able for soft deletes will require breaking changes to the db upsert functions, so I'm leaving that out.    It is messy enough updating the serialized metadata fields during a soft delete command.

Still needs:
- many more tests, especially against conjoined tenancy and doc hierarchies
- bulk import considerations: do we need to make sure there is consistency between the doc and the metadata columns with this path  (they are always consistent on read after import)
- decision on whether it is ok to cache metadata all the time.  It's the cleanest way to enforce read-only when saving changes, and this would allow `MetadataFor<T>` to use the cache before making a round trip, but there will be added memory costs (especially for lightweight session's `NulloIdentityMap`)

**Comment by jeremydmiller** [comment]
I'm merging this into #1337
