### ISSUE TITLE
Tenant & Timestamp are empty on events in AfterCommitAsync

### ISSUE THREAD

**Issue by Hawxy** [JasperFx/marten#1402]
Using Marten 3.10 + Marten.Nodatime

```csharp
    public class MartenEventListener : DocumentSessionListenerBase
    {        
        public override async Task AfterCommitAsync(IDocumentSession session, IChangeSet commit, CancellationToken token)
        {
            var events = commit.GetEvents();
            foreach (var @event in events)
            {
                //@event.TenantId is null & @event.Timestamp is DateTime.MinValue.
            }
        }
    }
```
The fields are populating correctly on the database, just not appearing here.

**Comment by oskardudycz** [comment]
@Hawxy Thank you for creating this issue, I'll try to check that asap.

**Comment by 5c0r** [comment]
After debugging, it seems 
- IChangeSet.Events TenantId and Timestamp was not changed, they are only there for deserialization. The timestamp was fine on the database since AppendEventFunction does not use event timestamp as default parameters.
- This happens for normal usage as well , not just with Marten.NodaTime

My assumption is that you would like the appended time to be exact when events are inserted in the database , and setting event.Timestamp = DateTimeOffset.Now after changes are applied would not be the best approach.

Possible future tests :
- Expected correct TenantId/Timestamp from ChangeSet after AppendEvents/AppendStream

**Comment by jeremydmiller** [comment]
Most of this was addressed by the V4 event appender changes, but I added a test to verify this behavior. Nothing to do with NodaTime usage.
