### ISSUE TITLE
CreateOrUpdate wants to control more than default schema?

### ISSUE THREAD

**Issue by hairymonkeynuts** [JasperFx/marten#1453]
We're running into an issue with Marten, when trying to apply table changes to the default schema, it also wants to inspect or change every other schema, some that the code shouldn't have access to. When it tries it generates an Access Denied error against the inaccessible schema. Even if we allow Select against the schema and tables it still errors. We are on 2.7.1 still (upgrading is currently problematic). I went through the release changes and didn't see anything related (though GH-1330 in 3.7.0 might help to a degree). We are using CreateOrUpdate for the schema. Is this expected behavior? I haven't been able to find much outside of the schema it is supposed to control.

thanks!!!

**Comment by hairymonkeynuts** [comment]
I'm just trying to understand why it is trying to control a schema that marten is not told to maintain. Anyone know?

**Comment by oskardudycz** [comment]
@hairymonkeynuts could you provide some reproduce steps? I'm not aware of the impact on the other schemas

**Comment by jokokko** [comment]
I have a vague memory of maybe bumping into this problem, but a repro would be nice indeed.

**Comment by hairymonkeynuts** [comment]
thanks for replying @oskardudycz!  Please bear with me... i'm on ops side and cannot view code due to compliance reasons.

We set up the DB schema (under 'public') with Marten and handle changes with it as well. We had a need to use DMS for some replication to S3 and created a schema for it under 'dmsschema'. This DMS schema is locked to only the DMS access role so the code utilizing Marten cannot access it.

Summarily:
Create DB, example_role (nosuperuser) is owner of DB
Set up Marten to CreateOrUpdate under default schema (public) utilizing the example_role to connect/login
Create a new schema in same DB, make owner of the this new schema some other role (role_y) 
Call Marten to check the schema of the DB. It should note the access denied to the new schema.

I hope this makes sense. thanks!!!

**Comment by jeremydmiller** [comment]
@hairymonkeynuts The queries that Marten uses against the metadata views in Postgresql are unfortunately impacted by the postgresql role permissions, and that can throw Marten off, but I'd expect that to err on the side of missing things.

I think you need to reconcile the actual Marten code configuration against your database setup. It's possible the schema name isn't configured the way you're expecting in the code. It's also possible that postgresql security setup is fooling Marten into thinking that some existing database schema objects don't actually exist.

I think I'd suggest dumping the SQL changes to a file and applying those changes manually or at least though something that automates the SQL execution rather than relying on runtime behavior of Marten. 

This kind of thing hasn't gone super well when the Postgresql security setup is complicated or really just different than the default setup

**Comment by jeremydmiller** [comment]
I'm taking the "bug" label off and marking this as a question.

**Comment by hairymonkeynuts** [comment]
Thanks, @jeremydmiller. That helps explain quite a bit for us. Appreciate the help and apologize for the delay on the response.
