### ISSUE TITLE
Question: `mt_events` Table Design Motivations

### ISSUE THREAD

**Issue by kerry-perret** [JasperFx/marten#1455]
I was looking at the SQL script [here](
https://github.com/JasperFx/marten/blob/0ccc54748849236c49ccb38fa3f1984b4a2f6efe/src/Marten/Schema/SQL/mt_stream.sql) and tried to understand the motivations behind the design of the `mt_events` table:

```
CREATE SEQUENCE {databaseSchema}.mt_events_sequence;

[...]

CREATE TABLE {databaseSchema}.mt_events (
	seq_id		bigint CONSTRAINT pk_mt_events PRIMARY KEY,
	id		uuid NOT NULL,
	stream_id	uuid REFERENCES {databaseSchema}.mt_streams ON DELETE CASCADE,
	version		integer NOT NULL,
	data		jsonb NOT NULL,
	type 		varchar(100) NOT NULL,
	timestamp	timestamptz default (now()) NOT NULL,
	CONSTRAINT pk_mt_events_stream_and_version UNIQUE(stream_id, version),
	CONSTRAINT pk_mt_events_id_unique UNIQUE(id)
);
```

Note: I've also been through [that piece of documentation](https://martendb.io/documentation/events/schema/#sec2).

**What is the purpose of the `seq_id` as a primary key?**

I don't really understand the purpose of the  `seq_id` as a primary key, since there is already an `id` column for which the values are generated on the client-side via [CombGuidIdGeneration](https://github.com/JasperFx/marten/blob/0ccc54748849236c49ccb38fa3f1984b4a2f6efe/src/Marten/Schema/Identity/CombGuidIdGeneration.cs). From my understanding, those values generated by that algorithm are both sequential and the probability of collisions are very low (plus from what I'm seeing there is already a unique constraint on the `id` column to avoid any possible redundant values anyway).

So why the `id` column set as a primary key wouldn't be enough? 

Additionally, I thought about potential concurrency issues, but I don't really see how does a `sequence` of `bigint` would do a better job here. A sequence might fall out of sync and have gaps anyway due to an expected failed transaction. I'm sure that I'm missing something out and I would like to better understand what was the motivation behind that decision.

**Why `seq_id` is not defined as `bigserial` column type?**

Also, I was wondering why the `seq_id` is not written as a `bigserial` column which behind the scenes does pretty much the same job (`bigint` sequence).

[8.1. Numeric Types - 8.1.4. Serial Types](https://www.postgresql.org/docs/9.3/datatype-numeric.html)
[9.16. Sequence Manipulation Functions](https://www.postgresql.org/docs/current/functions-sequence.html)

Again, I'm probably missing something out.

**Why the `type` column does not have an index?**

I know that an index might slow down a little bit the insertion speed but it might come in handy to filter out some events in a given stream based on their types, especially if that stream is becoming pretty big.

Is it about trade-offs and usage?

---

I'm sorry if my questions sound really stupid but I couldn't really figure out why that specific design has been chosen.

**Comment by jeremydmiller** [comment]
@kerry-perret You might want to phrase this more as suggestions than questions.

"Why the type column does not have an index?" -- I was much more worried about the insert performance at the time that was originally built, but that's probably worth thinking about in v4 because the async daemon (assuming that stays in) queries by type.

"Why seq_id is not defined as bigserial column type?" -- I can't say that I even knew about BigSerial

"What is the purpose of the seq_id as a primary key?" -- This one's a little more involved, and it's been several years since we went through all that. It's actually possible in Marten to configure whether or not you want the events to use Guids or numbers as the primary key. Don't remember why folks wanted that, but it was a big deal for Marten v2 for *somebody*. The async daemon depends on the `seq_id` as a table wide event id to track progress and that's critical, so that has to stay. I honestly don't remember why there's also a Guid key option, but that might have something to do with the C# code and needing a way to correlate objects in memory before the sequential id is assigned and absolutely nothing to do with SQL whatsoever.

**Comment by jeremydmiller** [comment]
@kerry-perret Okay, nevermind about the bigserial. Wouldn't really have made anything simpler because it was important to return all the new id's to the client in the function that appends events. Auto-incrementing didn't really help IMO, and with the "tombstone" idea we'll try to play in v4, even less so.

You probably shouldn't be trying to understand things by looking at just a database table without any other context here.

**Comment by kerry-perret** [comment]
First off, thanks a lot! That is super duper informative!

---

> @kerry-perret You might want to phrase this more as suggestions than questions.

Blurred lines 😄  (couldn't come off with a proper pun, thought about "quegestions")

In all seriousness, that was purely out of curiosity. I wouldn't dare to suggest anything serious until I manage to grasp every tiny little bit of detail (that may take a while (a long one), though).

---

_Why the `type` column does not have an index?_

>  I was much more worried about the insert performance at the time that was originally built, but that's probably worth thinking about in v4 because the async daemon (assuming that stays in) queries by type.

If you don't mind, I am also taking the liberty to add below what you told me on Gitter, if it could be of any help for someone passing by this "questionissue / issustion": 

> Oh, but about indexing type. It’s mostly inserts and few reads of that table. When there are reads using the type column in prodution usage, there would always be a WHERE clause against the seq_id column as well that first constrains the results against a 100-200 record range, so I don’t see an index on type as being desirable.

Your answer is sound, I thought about that too, that's exactly why I was wondering if it was due to usage.

---

_What is the purpose of the `seq_id` as a primary key?_

> This one's a little more involved, and it's been several years since we went through all that. It's actually possible in Marten to configure whether or not you want the events to use Guids or numbers as the primary key. Don't remember why folks wanted that, but it was a big deal for Marten v2 for _somebody_. The async daemon depends on the `seq_id` as a table wide event id to track progress and that's critical, so that has to stay. I honestly don't remember why there's also a Guid key option, but that might have something to do with the C# code and needing a way to correlate objects in memory before the sequential id is assigned and absolutely nothing to do with SQL whatsoever.

I see, things are pretty clear now.

---

_Why `seq_id` is not defined as bigserial column type?_ 

>  I can't say that I even knew about BigSerial

> Okay, nevermind about the bigserial. Wouldn't really have made anything simpler because it was important to return all the new id's to the client in the function that appends events. Auto-incrementing didn't really help IMO, and with the "tombstone" idea we'll try to play in v4, even less so.

It does makes sense to me now.


Thanks again!
