### ISSUE TITLE
Includes like RavenDb

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#146]
I can see that the option to do batched queries has now been implemented which is fantastic, would the ability to use Includes like RavenDb also be supported at any point?

I have many times where i need to load 2 or more documents in a single query, but i don't know the other document ID's until the result of the first is returned.

**Comment by jeremydmiller** [comment]
@phinett A couple other people have asked about this, and I think it's possible. I've been jotting notes on doing this in Marten this morning. I tried to sketch out other syntax ideas, but I'm leaning toward just copying Raven's syntax.

For everyone else, he's referring to: [RavenDb's Include feature](https://ravendb.net/docs/article-page/3.0/csharp/client-api/session/loading-entities).

**Comment by phillip-haydon** [comment]
Posted in the chatroom but posting here too. 

```csharp
IList<Member> members = null;
IList<Album> albums = null;

var photos = session.Query<Photo>()
                    .Where(x => x.CategoryId = 123)
                    .AndFetch<Member>(x => x.MemberId, () => members)
                    .AndFetch<Album>(x => x.AlbumId, () => albums)
                    .ToList();
```

My 2c on api, taken from NHibernate's QueryOver<T> / Criteria apis. 

http://www.philliphaydon.com/2011/04/13/nhibernate-querying-relationships-are-depth/

**Comment by phillip-haydon** [comment]
![discussion](https://cloud.githubusercontent.com/assets/895629/13013750/c18439fe-d1eb-11e5-83be-6c39e3b1ecd0.jpg)

**Comment by jeremydmiller** [comment]
This is also related to GH-150.

**Comment by jeremydmiller** [comment]
Before we (I) do even the slightest bit of coding work on this, what does everybody think about the options to either:

1. Effectively copy RavenDb's "Include" feature. This means we will quietly execute the normal query with
    some joins to grab the additional data, stuff the extra documents into the underlying IdentityMap, then
    have the user access the included documents already fetched through `IDocumentSession.Load(id)`
1. Use something more like NHibernate's `QueryOver` syntax where the additional documents are fed
    out through `out` parameters. 
1. Depending on how we end up implementing GH-150, have the related documents attached directly to
    the documents being queried directly.

My thoughts:

* I think the RavenDb approach is the simplest to implement, but not by a huge amount. I think it would be confusing to many developers because it's not obviously clear that you're avoiding extra database calls or how to use that feature. The pro of us already being familiar with the feature from RavenDb doesn't carry much weight if we're building Marten for the longer term.

* With the NH flavored approach, I think it's more explicit what's happening, but we'd need to be careful about what we actually return. Is it a list, or a Dictionary of the docs organized by Id? What if it's only one? And I hate out parameters from some very distasteful memories of coding in Fortran in college;)

* I think I actually prefer the idea of having an actual property getter/setter for the relationship and just setting the value with the included document as you load the parent. Again, I think this depends somewhat on GH-150. What if we end up requiring an FK relationship in order to opt into this behavior?

Oh, and at least for right now, I am absolutely saying that the first version of this only goes one deep in the relationships before we tackle N-deep.

**Comment by phinett** [comment]
Probably more work, but would it be possible to do a hybrid....so maybe something like:
`Session.Query<MyObj>().Include(_ => _.ChildIds, out children);`

Not sure how it would return the out parameter, could it not be specified somehow with generics like so?
`Session.Query<MyObj>().Include<List<ChildObj>>(_ => _.ChildIds, out children);`

But also support the same syntax as RavenDb and allow to retrieve from the IdentityMap.
`Session.Query<MyObj>().Include(_ => _.ChildIds);`

**Comment by jeremydmiller** [comment]
@phinett That's not a "hybrid", that's implementing it both ways!

**Comment by jeremydmiller** [comment]
Here's a 3rd option that I think @CoreyKaylor might have been hinting at before. Say we make it pretty similar to the latest version of the [batched query](http://jasperfx.github.io/marten/documentation/documents/batched_queries/). 

Something like:

```
var group = session.CreateGroupedQuery<User>();

var users = group.Where(x => x.Role == "Admin").ToList(); // if sync, returns Lazy<IList<User>>

// fetch, but separately
var regions = group.Include(x => x.Region) // if sync, returns Lazy<IDictionary<object, Region>>

// attach directly to the User object's "Region" property instead
group.Attach(x => x.Region)

group.Execute();

// now you can use the individual results

```

In the case of async, we'd return Task<T>'s instead, very similar to how we do the batched query.

**Comment by phillip-haydon** [comment]
I opt against RavenDB style because IMO it's not obvious.

Currently in RDB when you call `Load<T>(..)` it's cached for that session, any more calls will grab the same version. Currently this isn't in Marten (correct me if I'm wrong)

Which means we need to track already queried results for the life time of the session. Then evict when we need to re-query the same object. 

-----

I don't like the out param and actually favor the QueryOver method using assignment instead. 

```
List<Category> categories = null;

session.Query<Product>().Include(p => p.Category, () => categories);
```

While this is less like Batch, I personally like the syntax better, to me it feels more obvious what is happening. 

-----

The batching one I like more than the RavenDB one, but less than QueryOver because I have feel like I have to build up a query to execute.

Batch feels like I'm doing a lot of work in preparation, where QueryOver I feel like I'm just grabbing what I need. (if that makes sense)

-----

3rd I think we need to ensure a helpful error message is thrown when we try to include on results that are not mapped properly.

**Comment by jeremydmiller** [comment]
@phillip-haydon "it's cached for that session, any more calls will grab the same version. Currently this isn't in Marten (correct me if I'm wrong)" -- Marten already supports the "Identity Map" concept where you do get the caching by Id per session. `DocumentStore.QuerySession()` or `DocumentStore.LightweightSession()` will give you a session w/o the identity map caching.

I'm still reading over the rest of your comment;-)

**Comment by jeremydmiller** [comment]
@phillip-haydon Agreed on being more explicit, and I'm not a huge fan of depending upon the identity map caching. I can live with using the assignment via Lambda.

I still wanna consider the additional option where it just adds the related document directly to whatever property or field that has the reference.

**Comment by phillip-haydon** [comment]
You could do:

```
List<Category> categories = null;

session.Query<Product>().Include(p => p.CategoryId, x => x.Category);
```

And then in the mapping we do something like:

```
_.Schema.For<Product>()
  .ForeignKey<Category>(x => x.CategoryId, CanBeNull = true/false);
  .IgnoreProperty(x => x.Category);
```

Where IgnoreProperty ensure's it's never serialized. (I hate attributes :D)

**Comment by jenspettersson** [comment]
What if you don't want/have a `Category` property on the `Product` but only an Id reference?

Not really a fan of the `.IgnoreProperty(x => x.Category)` as if you just load the `Product` as a regular load, will the `Category` property be null?

In the above example it looks like you have both a `CategoryId` and a `Category` property on the `Product` and that's seems a bit confusing to me...

```
session.Query<Product>().Include(p => p.CategoryId, x => x.Category);
```

Not sure which way I personally like the most though... At first glance, the `.AndFetch<T>` syntax looks quite nice.

**Comment by phillip-haydon** [comment]
@jenspettersson - I'm suggesting with the lambda you can have both scenarios:

```
session.Query<Product>().Include(p => p.CategoryId, x => x.Category);
```

This would map the Category directly to the Product instance. But you need to ignore the Category during serialization. I proposed having an `IgnoreProperty` to mark it for exclusion.

The problem with this whole design tho is that your Product now doesn't have a reference to a Category, it's got a relationship to the category, its become part of the root aggregate which to me is wrong. But people like to do it.

It also means that mapping is much more complex because you want to store the category in 1 table, but then map it to the product. In an EF/NH world you could use proxy objects to create an in-memory Category which has the mapped Id `product.Category.Id` but for fast serialization of the document to JSON this is far too complex and I believe performance is far more important than 2 properties on the document.

In the scenario where you Don't want the category on the product. 

```
List<Category> categories = null;

session.Query<Product>().Include(p => p.CategoryId, () => categories);
```

This would map it to the variable. This syntax is 100% hijacked from NHibernate and (my personal opinion) is to favor this over RavenDB or Batch query solution. 

However if the decision is to go with the batch solution I'm happy with that too. We must make sure we don't sacrifice performance during serialization/deserialization tho.

**Comment by jenspettersson** [comment]
I think it's the "category becomes part of the root aggregate" that I also feel is wrong and that's why I didn't really like that option. 

The lambda syntax looks kind of nice actually, I think it's quite clear on what's going on.

I didn't quite get the `CreateGroupedQuery<T>`, but I think that's because the syntax is so different from the `Include(...)` syntax I've been used to.

**Comment by CoreyKaylor** [comment]
I vote for @phillip-haydon 's recommended approach. It seems both explicit when necessary and understandable.

**Comment by jeremydmiller** [comment]
I'm voting for @phillip-haydon 's approach, but I might tweak the API signatures a little bit. 

I don't think there's any situation where we'd need - or want to - use a dynamic proxy for relationships. Either have Marten attach related documents during load or don't. No lazy here.

As for ignoring a property in serialization, you'd need to do that in the Newtonsoft configuration or whatever Json serializer you're using. Would mean exposing Newtonsoft directly, or at least feeding it into Marten instead of using the ilmerge'd version.

**Comment by phillip-haydon** [comment]
@jeremydmiller just tested out the `Include` stuff. 

I get a SQL Exception:

> Oh noes! ---> Npgsql.NpgsqlException: 42702: column reference "data" is ambiguous

So I printed the Command (AWESOME FEATURE)

```
select d.data, d.id, member_id.data, member_id.id 
from mt_doc_photo as d 
INNER JOIN mt_doc_member as member_id 
ON d.member_id = member_id.id 
where ((d.is_private)::Boolean = False) 
and (data @> '{"State":2}') 
order by CAST(d.data ->> 'Id' as integer) desc 
LIMIT 50  OFFSET 0 
```

So the two columns returned, are both called `data` and `id`, the includes will need to be aliased.

`member_id.data as member_id_data, member_id.id as member_id_id`

**Comment by jeremydmiller** [comment]
@phillip-haydon Got it, same thing that @phinett hit. @nieve is looking at this one. We just need to get the table alias into the containment operator construction.

This is our offender:

```
and (data @> '{"State":2}') 
```

**Comment by phillip-haydon** [comment]
OH, I didn't even spot that one. Ok cool.

**Comment by nieve** [comment]
PR #239 fixes this.
