### ISSUE TITLE
[Question] : Marten connection handling

### ISSUE THREAD

**Issue by MartinNuuday** [JasperFx/marten#1461]
In the Marten documentation it is stated that a db connection lives for the duration of the session. It is opened at the first call to the database and not closed before the session is disposed.
(Btw.  Marten actual seems to close the connection after a SaveChanges and will reopen it if another DB operation is done after that.)

Lets say you got the following (simplified) code:

        public async Task<Customer> GetCustomerAsync(string customerId)
        {
            using var session = _store.OpenSession();

            //Super fast call to db
            var customer = await session.Query<Customer>()
                                        .Where(c => c.Id == customerId)
                                        .FirstOrDefaultAsync();

            if (customer == null)
            {
                //Annoyingly slow call to old legacy mainframe from hell 
                var legacyCustomer = await _slowLegacyBackend.GetCustomerAsync(customerId);
                customer = Map(legacyCustomer);

                session.Store(customer);
                await session.SaveChangesAsync();
            }

            return customer;
        }

The Query and SaveChanges will usually complete within a few milliseconds where as the call to the legacy system will take 2-10 seconds.
Now we are holding up a connection to Postgres for seconds where as we really only needed to have it allocated for a few milliseconds.

If the code above is used in some Web Api where at peak can get a few hundred calls/second we could deplete the available Postgres connections even through the database has very little load.

One solution could be to manually handle the db connection (simplified):

        public async Task<Customer> GetCustomerV2Async(string customerId)
        {
            await using var connection = new NpgsqlConnection(_connectionString);
            using var session = _store.OpenSession(new SessionOptions { Connection = connection });

            await connection.OpenAsync();
            var customer = await session.Query<Customer>()
                                        .Where(c => c.Id == customerId)
                                        .FirstOrDefaultAsync();
            await connection.CloseAsync();

            if (customer == null)
            {
                var legacyCustomer = await _slowLegacyBackend.GetCustomerAsync(customerId);
                customer = Map(legacyCustomer);

                session.Store(customer);
                await connection.OpenAsync();
                await session.SaveChangesAsync();
                await connection.CloseAsync();
            }

            return customer;
        }

So the questions are:
1)	Would it be Ok to manually handle db connections like shown above, or can there be some unwanted side effect?
2)	What is the reason for keeping connections open for the lifetime of the session?. Npgsql already handles pooling of connection, therefor open/close is very fast (like millions/sec). 
The documentation states that that because you got a “sticky“ connection you can use serializable transactions. I understand that, but in my experience serializable transaction is something that
is not often used.

**Comment by jeremydmiller** [comment]
@MartinNuuday Hey, sorry we've been so slow to get back to you on this. A couple thoughts:

* Yeah, I'd avoid messing around with the connection mechanics of Marten like your second code sample above
* The session is meant to be short lived, and the connection stays open the whole time so that you get consistent reads along with the commit. It's also possible to use serializable transactions that would open the connection earlier. And serializable is used frequently enough that this stays in place
* If I were you, I might be opting for a stateful saga of some sort or...
* Open a QuerySession to get the original Customer, and close that. Then call the legacy system, and use a separate DocumentSession to persist the returned document. That way you're playing within the public API and behavior of Marten and still being more efficient about the connection usage.

**Comment by jeremydmiller** [comment]
This was just a question, so I'm closing.
