### ISSUE TITLE
(Question) store.Schema.ApplyAllConfiguredChangesToDatabase(); does not apply DDLTemplates

### ISSUE THREAD

**Issue by smaktacular** [JasperFx/marten#1474]
Hi,

We put a DDL template in the folder Templates in our project folder and and it is being read when we use  
 `_.DdlRules.ReadTemplates("Templates");`
and included in the ddl generated via 
`var ddl = _store.Schema.ToDDL(true);`

We then tried to apply the DDL template and assumed that the template would be used when calling 
`_store.Schema.ApplyAllConfiguredChangesToDatabase();`

But this is not happening. Is there something we might be missing regarding the use of ApplyAllConfiguredChangesToDatabase() or some restrictions that apply to the method?

**Comment by jeremydmiller** [comment]
Just out of curiosity, what are you embedding into the DDL templates? Something around permissions?

And @oskardudycz @mysticmind, I'll deal with this soon.

**Comment by jeremydmiller** [comment]
@smaktacular Thanks for your response. I got into the code this evening for this (finally), and it's the exact same code to write the patch SQL that you'd get in any case. AFAICT, the DDL templates are applied to the ApplyAllConfiguredChangesToDatabase() call. I think we need a little more information.

Are the DDL templates working in other scenarios? Could this be a relative v. absolute path issue?

And I'd probably ask you to look through the open issues because I swear there's already something open for exactly what you're doing for TimescaleDB. Wouldn't hurt to weigh in on that, and we can make that a priority in v4.

**Comment by smaktacular** [comment]
@jeremydmiller I feel like I'm missing something really obvious here 😁. 
I added a repro project under [Repro](https://github.com/smaktacular/marten_template_repro). 

The issue you are refering to, was it this one? [#1343](https://github.com/JasperFx/marten/issues/1343) ?

**Comment by mysticmind** [comment]
@smaktacular thanks for the repro for this issue.

@jeremydmiller I tried zeroing on this issue and observing the following:
- DDL template gets added only for the case of `dump` via the CLI tool i.e. if the call uses `schema.ToDDL(...)`
- `ApplyAllConfiguredChangesToDatabase` and also the `patch` via CLI only generate DDL for the schema objects and ignores DDL templates.

In summary, `feature.WritePermissions(...)` call is ignored for the schema patch related API code paths. Possibly there is a reason for this since patch API can't track or compare what the user adds via the DDL templates.

Can you please run through the above and let me know your thoughts?

**Comment by jeremydmiller** [comment]
@mysticmind I'd guess that it's just an oversight and not anything too purposeful. I traced this code though and thought I found where the DDL templating was done, but I wasn't thinking about the permissions stuff as a separate step.

**Comment by jeremydmiller** [comment]
I think I'm making the unilateral decision to kill off all the DdlTemplate support. Let folks just edit SQL files if they really want this.
