### ISSUE TITLE
Proposal: Eliminate magic insert or upsert tracking on Id

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1516]
In current Marten, when you call DocumentSession.Store(document), it checks for the existence of an assigned identity, and if there is one, assumes in some cases that a document is being inserted rather than an "upsert".

I wrote this feature at some point from a git blame, and I vaguely remember thinking it was a mild improvement to efficiency, but it's magic.

Would anybody mind if we eliminated this behavior in v4? It's a little bit of magic that could easily spoof a user, and it's making some of the internals harder than it should. The upsert in Postgresql is very efficient, so it doesn't matter much IMO.

**Comment by oskardudycz** [comment]
I'm fine with changing that for the Store method, if it won't decrease performance significantly.
What about Insert method? Currently, it's using Store with identity map internally? Will it also do always upserts? That might be conceptual conflict with what user expects to happen.

**Comment by mysticmind** [comment]
@jeremydmiller I ran through the current code and I am fine with removing that behavior. With the new proposed change, will it always be an upsert immaterial of assigned or not? Note that the storage store method still uses the identity map.

If the above changes are going to result in just upsert always then I would propose to rename the method also as `Upsert` so that it does not result in confusion between `Store` and `Insert`. I do understand that Store allows for adding heterogeneous document types. I am more thinking around standardizing the names of the methods.

**Comment by jeremydmiller** [comment]
Correct, if you use the `Store()` method, it's an upsert no matter what with this proposal. 

As for renaming `Store()` to `Upsert()` or `InsertOrUpdate()` (?), do it now I suppose. I'd leave `Store()` in place and make that `[Obsolete]`.

The `Store()` name was ripped off from Raven Db, and didn't really matter before we had separate `Insert()` or `Update` functions.

**Comment by oskardudycz** [comment]
@jeremydmiller @mysticmind I'd personally prefer to keep `Insert` and `Update` method. I can imagine cases where user would like to get an explicit failure when record does not exist. Especially for the concurrency cases, it might be dangerous to just do upsert. 
If we don't want to use identity then maybe we could provide a parameter to upsert function with expected behaviour (`Store`, `InserOnly`, `UpdateOnly`)?

**Comment by jeremydmiller** [comment]
Nobody is proposing eliminating `Insert` and `Update`, just renaming the `Store()` to something that makes clear it's an `Upsert`, right? You already have separate, distinct methods for whether or not it's an insert, update, or upsert. There's no need to add that extra parameter.

I'd rather leave the signatures alone, but I'm willing to entertain changing Store() to InsertOrUpdate() or CreateOrUpdate() or leave it alone.

I just wanted to get rid of the magic "I can tell it must be an insert by the missing id" logic if we can. But that's also not a huge deal if we decide we want to keep it.

**Comment by oskardudycz** [comment]
If that change won't change the Insert logic then I’m fine (I was asking as it uses Store underneath).

Regarding the naming, I think that users are familiar with our naming. I understand that it’s not ideal as it’s not telling precisely what’s doing but that would require users to do a lot of changes. Maybe a better option would be adding an extension method as syntactic sugar?

**Comment by jeremydmiller** [comment]
Insert() is not the same functionality as Store() and does not use Store() at all. Store() had some magic logic that would opt to actually use the Insert() logic instead of the normal Store() if there was no prior identity. That very last part is all I want to get rid of for v4.
