### ISSUE TITLE
Make DocumentSession thread safe?

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#178]
In reality, this work would mostly be in IUnitOfWork. The point is if for some crazy reason you're continuing to add documents to a DocumentSession while a 2nd thread is calling SaveChanges(Async), you could easily get some inconsistent results.

Pros: Thread safety, less weird stuff going wrong
Cons: More complexity, the code will be slower w/ all the locks

Potential workaround: Make unit of work smart enough to only clear changes that were definitely part of the unit of work. Maybe replace the unit of work when trying to commit?

**Comment by mariotoffia** [comment]
Isn't it better to make getting a DocumentSession as "cheap" as possible and make them non thread safe and let the "user" code handle interthreading issiues? Most frameworks that I've been working with have had this assumption since kernel locks are cheap and it is easier to optimize the user code instead of generic support which might be a bit "blunt".

Makes sense?

Cheers,
 Mario

**Comment by jeremydmiller** [comment]
I'm agreeing with @mariotoffia and shutting this down. One way to clean up the GH issue backlog;-)
