### ISSUE TITLE
problem for rendering snippet on page "Immutable projections as read model"

### ISSUE THREAD

**Issue by p30help** [JasperFx/marten#1969]
I checked the page "[link](https://martendb.io/scenarios/immutable-projections-read-model.html)" multi-time but I can't see code examples because they don't render properly.
please solve it

**Comment by mysticmind** [comment]
@p30help The code samples will need to be re-looked at due to the whole event store/projections stuff revamped completely in v4. In the interim, I have added a TODO note as below in the docs page to add clarity around the reason for the code samples being unavailable in the page.

<img width="1427" alt="Screenshot 2021-11-16 at 2 52 46 PM" src="https://user-images.githubusercontent.com/2864208/141958310-7bfd7306-49d8-4f85-84f1-819559a084d3.png">
