### ISSUE TITLE
Aggregate Projections and Soft-Deletes

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#1992]
I know this came up on Gitter, but wasn't captured in an issue. If a user does an aggregate projection, makes the aggregate type soft-deleted for some reason, then the aggregate is deleted, then resuscitate the aggregate, the async daemon and inline projections would never "un-delete" the aggregate document. Just a case we didn't consider when building everything for V4.

**Comment by jeremydmiller** [comment]
Blech, it's just not easy. Or it is easy, but nasty inefficient because we don't have any easy way to know what's already deleted. I'm temporarily making this blow up on assertions.

**Comment by jeremydmiller** [comment]
I'm putting this back for now, thought up a way to do this.

**Comment by lukedukeus** [comment]
@jeremydmiller 

I'm not sure if this is the correct place for this, but if I configure marten like this:
```
builder.Services.AddMarten(options =>
{
    string? connectionString = builder.Configuration.GetConnectionString(Constants.ServerDatabaseName);
    if (string.IsNullOrEmpty(connectionString))
    {
        throw new ArgumentNullException(nameof(connectionString));
    }
    options.Connection(connectionString);

    options.UseSystemTextJsonForSerialization();

    if (builder.Environment.IsDevelopment())
    {
        options.AutoCreateSchemaObjects = AutoCreate.All;
    }

    options.Events.AddEventType<UserCreated>();
    options.Events.AddEventType<UserUpdated>();

    options.Schema.For<User>().SoftDeleted();

    options.Projections.Add<UserProjection>(ProjectionLifecycle.Inline);
});
```

And my projection looks like this:
```
    public class UserProjection : SingleStreamProjection<User>
    {
    }
```

I get this error:
```
Marten.Exceptions.InvalidProjectionException: 'AggregateProjection cannot support aggregates that are soft-deleted'
```

I can't find any documentation that says SingleStreamProjections do not support soft deletes. It looks like [this ](https://github.com/JasperFx/marten/pull/2125)PR fixes this issue. Is it that soft delete is possible and I have something misconfigured, or it is not supported?

Please excuse my ignorance, I am aware I could implement soft deletes myself by just adding an `IsDeleted` prop to every model, but if this is possible via the marten APIs, I'd prefer to use them.

**Comment by lukedukeus** [comment]
@jeremydmiller Any news?

**Comment by helder-abi** [comment]
I have same problem

**Comment by lukedukeus** [comment]
@helder-abi I found that Jeremy is more responsive over on discord. Link is [here](https://discord.com/invite/critter-stack-net-1074998995086225460)

I asked the same question in the discord channel, and found that SoftDeletes are only supported if the projection is a `CustomProjection`. The document [here](https://martendb.io/events/projections/custom-aggregates.html#explicit-aggregations) shows an example of a `CustomProjection` with soft deletes enabled. I have yet to try implementing my own, but it works in the demo code.

P.S. I find github issues and stack overflow questions much more searchable than discord channels. I know that someone has run into this exact same issue before, because the example I linked exists. Unfortunatly, I wasn't able to find it.  I think this ties into a bigger issue (see #1701). I have hesitations on starting a new project using marten, because I am worried I might run into a pitfall like wanting to have soft deletes with projections, and be unable to find any support or being cornered into hacks and workarounds. With something that is so base in the tech-stack, I seriously consider writing my own event sourcing solution with efcore interceptors.

**Comment by mysticmind** [comment]
@lukedukeus  Few things, if you put some question on a closed issue in 2022, how on earth are you setting expectation for the maintainers to respond. You can raise a fresh issue or raise a question in GitHub discussion or Discord (this being the fastest since many of key folks hand out there). In retrospect I see that have already asked so many questions in Discord and got clarification. 

> I think this ties into a bigger issue (see https://github.com/JasperFx/marten/discussions/1701). I have hesitations on starting a new project using marten, because I am worried I might run into a pitfall like wanting to have soft deletes with projections, and be unable to find any support or being cornered into hacks and workarounds. With something that is so base in the tech-stack, I seriously consider writing my own event sourcing solution with efcore interceptors.

https://jasperfx.net/ is a company run by Jeremy which provides formal support for a fee. So you can always pay and get formal support rather than venting your frustration here. Also "soft deletes with projections" is a not a standard use case in event sourcing and as you are already aware by now that there are ways to achieve this. Feel free to pickup whatever suits you and run with it.

**Comment by lukedukeus** [comment]
Babu, thanks for taking the time to respond, and guidance on Discord. I understand now that most of the discusisons regaurding marten are happening over on Discord, but at the time of writing the original comment, I was not aware of the Discord channel. In my experience with other OSS projects, it is standard to open a github issue to ask for help, or if an existing issue already exists, comment on that. It is clear that marten is a powerful library and I see it is endorsed by many in the dotnet space, but the biggest hurdle for me has been finding documentation on how to use it effectively. It might be worthwhile updating the README.md to tell people that if they have questions, they should go to Discord, or add an issue template that says something like this. To newbies like myself, I did not understand why soft deletes and projections would not be a standard use case, and I thought that it was possible because the comments of the linked PR. I see other people are running into this to, so it might be a good idea to update the soft-delete docs stating that it cannot be used with aggragate projections.

#1701 Asks why more people aren't adopting marten, and for me it isn't any technical limitation, instead the hard part is transitioning from years in the event-driven paradigm to event-sourcing. The Discord chat has been extreemly helpful to discover what is possible, and figure out the best patterns to follow.

**Comment by mysticmind** [comment]
@lukedukeus Appreciate your response and feedback. Acknowledge the motions of what you have been through. We will take steps to update the README accordingly. With regards soft-delete with projections, we will update the docs to reflect what is available as a functionality. 

That said, anyone coming into event sourcing will have a big hurdle understanding the nuances of implementing something/usage so it is always a big learning curve. Once you settle, everything would look clear and simple. So I would want you to have patience and understand that not all problems are Marten problems and it is more around how you think about the problem and figure out an idiomatic solution using a tool at hand like Marten.
