### ISSUE TITLE
NgramSearch doesn't handle mt_grams_vector function outside of public schema

### ISSUE THREAD

**Issue by claudiolassala** [JasperFx/marten#2398]
I had Marten configured to use separate read and write schemas (inspired by GoldenEye). 

NgramSearch fails to find the mt_grams_vector in my "read" schema. When building the WhereFragment, it doesn't handle looking for that function anywhere but in the "public" schema.

**Comment by apereiratl** [comment]
Well, the functions are added using the built-in marten functionality. Are you saying you expect these functions to be added to all schemas?

**Comment by mysticmind** [comment]
I have zeroed on the issue. This will require the following changes:
- Access to database schema in the https://github.com/JasperFx/marten/blob/81cf3c2b3c7992bbd199f2325d94dd81ab7d5c13/src/Marten/Linq/Parsing/Methods/NgramSearch.cs#L23 so that we can quality the ngram search related functions to use the one from the schema.
- Also the SQL files (`mt_grams_query.sql` and `mt_grams_vector.sql`) will need to be fixes to ensure they are qualified with the schema name for function usage.
