### ISSUE TITLE
Optimistic concurrency not working

### ISSUE THREAD

**Issue by FrankIversen** [JasperFx/marten#2609]
I have activated optimistic concurrency but even though I have only one thread running, which should yield zero concurrency exceptions, I get concurrency exceptions.

I have made a sample project.
https://github.com/FrankIversen/martenexample/tree/master/TestMarten  

To reproduce input a connection string for db in program.cs, then run the code. A loop will start. The first record will inserted succesfully if the id is not already in the database. If the record is not in the database the loop will fail in the first goaround.

It is my first time using Marten so I definitely dont rule out that I have done something wrong. Hope you can help :)

**Comment by oskardudycz** [comment]
@FrankIversen I added the PR showing how to use Marten optimistic concurrency correctly to your sample repo. See: https://github.com/FrankIversen/martenexample/pull/1. 



To be able to use the Optimistic Concurrency check behind the scenes, Marten must load the document first. The initial store was working well; the expected version was null because the document didn't exist. As we didn't load the new, generated one, it still provided the null as expected version (because we were recreating a new document each time).

Besides that, I provided examples of how to resolve tenants and used IDocumentSession instead of DocumentStore in the repository.

I'm closing the issue, as everything works as expected, but feel free to send feedback, follow up questions here or on Discord.
