### ISSUE TITLE
Make easier injecting services to Projections

### ISSUE THREAD

**Issue by oskardudycz** [JasperFx/marten#2638]
Seeing how many times it's popped up in Discord, I think that it's time to bring back ye-olde `LazyLoadedProjection` from v3, maybe in a bit smarter way. 

Per @jeremydmiller on Discord:

> Might look at IConfigureMarten as a way to do that a little easier. Something like AddMarten().AddProjectionWithServices<T>(lifetime); that smuggles in an IConfigureMarten that would then be applied. Possibly easier mechanics than the old lazy projection approach in v3

**Comment by AndyPook** [comment]
given critter things prefer a "method convention" approach for some things (rather than interfaces and ctor injection)
maybe something like the `[FromServices]` idea from aspnetcore would be appropriate. Or: if it's not in the convention, try to resolve from the service provider

For a bit of a hack, see my DI "solution" in https://github.com/JasperFx/marten/issues/1670#issuecomment-1665259677
it works for me and my situation. I am sure that there are situations where it will trip up over (conflict with) how marten does things

**Comment by jeremydmiller** [comment]
I'm still voting to do this through the solution I outlined on Discord. So something like:

```csharp
services.AddMarten( configuration )
     // This would use the IConfigureMarten approach, and the projection itself
    // is essentially a singleton
    .AddProjectionFromServices<T>(AsyncLifetime)();

```

I'm not enthusiastic at all about any kind of method injection through the projection method signatures. So I'm a 100% ixnay on a signature like:

```csharp
Task Apply(EventType e, AggregateType, [FromServices] ISomeService);
```

That way is madness and endless complexity managing the service lifecyles. Let users who really have to do stuff like this be completely responsible for managing the service lifecycles with IScopedServiceFactory if they really need that. 

It might make much more sense to have a base class helper for that for the first class subscriptions. Otherwise, I'd push folks to either assume the DI dependencies are singletons.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] New `AddProjectionFromServices<T>(AsyncLifetime)` extension method to add projections with services
- [ ] Bring in the extensions from @AndyPook w/ tests
- [ ] Update docs
