### ISSUE TITLE
Marten commandline >= 6.2.0 ignores ShardTimeout flag when using one letter alias '-t' 

### ISSUE THREAD

**Issue by StevenVerwerft** [JasperFx/marten#2780]
Hi,

When rebuilding projections prior to Marten Commandline v6.2.0 we could use a flag -t to increase the shard timeout. After upgrading to 6.2.0 we noticed timeouts when rebuilding our projections, although we still used the same command with -t option. This might be related to the new TenantFlag option that has been introduced (suggested by Matthias Vdb in discord https://discord.com/channels/1074998995086225460/1074999076896112661/1173596686866726993).

I couldn't find a test in marten to easily reproduce this behaviour. But we can reproduce the issue when inserting an invalid value for ShardTimeout using both -t as --shard-timeout options:
e.g.
`dotnet run -- projections -r -t invalid123  ` => this runs without issue

`dotnet run -- projection -r --shard-timeout invalid123 ` => throws invalid shard timeout value exception 

Kind regards, Steven

**Comment by Jentonic** [comment]
My team experiences the same issue. Our current workaround is downgrading to 6.1.
Full alias seems to also work in the meantime.

**Comment by mysticmind** [comment]
Yes, the issue at hand is due to `TenantFlag`, Oakton by default uses the first letter as the short alias for argument. This results in a conflict between `Tenant` and the explicit flag defined for `ShardTimeout`. I will be making a change to remove the short alias `t` for ShardTimeout and make it only use the long alias.
