### ISSUE TITLE
Change LoadMany() to prevent user confusion

### ISSUE THREAD

**Issue by phinett** [JasperFx/marten#282]
If i pass a list of strings to LoadMany<T>().ById() it fails with:
System.NotSupportedExceptionThis .NET type is not supported in Npgsql or your PostgreSQL: System.Collections.Generic.List`1[System.String][]

Converting the list to an array works fine, i'm presuming this is a bug.

Not tested Async, but assume it's the same.

**Comment by jeremydmiller** [comment]
@phinett Check the signature of the `ById()` method. It's `ById<T>(params T ids)`, and that's why it can't handle the `List<string>` because it thinks that just means that that is the element type of T.

So this isn't a bug per se, but quite possibly an API usability issue. We can talk about an overhaul of `LoadMany()` syntax on the way to 1.0. I wanted to do something about it anyway. Maybe to hardcode the four allowable id types (int, long, Guid, string) as overloads. That might stop all of this trouble.

**Comment by phinett** [comment]
Yes I see that now, probably would be better sticking to well defined choices from a usability point of view.

**Comment by nieve** [comment]
It's not the first nor the last api to have this issue. Personally I'm a fan of methods taking in params- maybe it's just a case where the exception message should be a lot more explicit?
