### ISSUE TITLE
Marten 7.3 ScopedProjectionWrapper doesn't pass the projection name to the inner wrapper

### ISSUE THREAD

**Issue by murlakatam** [JasperFx/marten#3058]
Inside ScopedProjectionWrapper<> there is a method resolving published types 

public IEnumerable<Type> PublishedTypes()

![image](https://github.com/JasperFx/marten/assets/38276/74e3573b-5323-4c68-981c-749e88767c81)

it creates another wrapper that doesn't respect a custom projection name passed through AddProjectionWithServices
and defaults to the type name 
![image](https://github.com/JasperFx/marten/assets/38276/a504a4fc-e4e1-4f3a-a298-e66b663eacb7)

**Comment by jeremydmiller** [comment]
@murlakatam I'm guessing the real issue here is that the daemon isn't using the correct projection name? The detail you called out in the screen shot is irrelevant to that and doesn't do any harm. What's the real outcome that's causing you trouble? Just the progression tracking names being incorrect?
