### ISSUE TITLE
Add Metadata Columns

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#360]
Add a column for last_modified, etag, and just make the type field mandatory. Doing that cuts out a *lot* of complexity.

As part of this work, test bulk loading documents in hierarchical storage.

Related to #35 and #256 

Also do something to make it easy to get at the metadata for a document. After only some admittedly shallow analysis, I think I vote for doing this on IDocumentSession and having the data tracked on the identity map. More thinking about that before we do anything.

**Comment by jeremydmiller** [comment]
For the metadata tables, do we want this on every single table? It makes the coding a lot easier if we do, but it will come at *some* kind of performance cost.

- [ ] last_modified -- timestamp of the last write, easy money
- [ ] dotnet_type -- assembly qualified name of the .Net type? There is also the `mt_doc_type` column we use for hierarchical storage, but that relies on a type alias name rather than the full .Net type, and I'd want to keep it that way. Do we wanna just make mt_doc_type be used across the board? We *could* add another metadata table that tracks the actual .Net type to the type alias. 

- [ ] version -- I still think we wanna make the usage of offline optimistic versioning be opt in on a per document basis, but what if we do add a UUID version field on every document? RavenDb uses Guid for their etag's, and even though it's ugly, it is helpful.

**Comment by CoreyKaylor** [comment]
I think all of these are probably necessary to some degree. Even if you're opting into optimistic concurrency to enforce update where clause constraints, it would be useful for them to exist when you haven't opted in.

**Comment by jeremydmiller** [comment]
The versioning is naive right now, jsut a new Guid on every insert

**Comment by ejsmith** [comment]
Sorry to comment on an old issue, but I found this while trying to figure out why Marten is using Guids for document versions. It looks like it was modeled after RavenDb, but RavenDb had guids because it wanted document versions to be unique and sequential across the entire system and used for etags. They have actually since [changed in 4.0](https://ayende.com/blog/178625/ravendb-4-0-the-etag-simplification) to simple incrementing longs.

It seems like an incrementing long is a much nicer and simpler way to do optimistic concurrency. Are there other reasons for using a Guid?
