### ISSUE TITLE
security / permission model

### ISSUE THREAD

**Issue by mdissel** [JasperFx/marten#410]
If we compare the features between ravendb and marten, a security/permission model is missing in Marten.
Maybe add support for this very powerfull postgresql extension to Marten (maybe as a separate module if users can't install a new extension into postgresql)

https://github.com/arkhipov/acl

This extensions support the Windows NTFS permissions model (including inheritance and custom permissions)

**Comment by jeremydmiller** [comment]
@mdissel It looks cool, but would we really need to do anything in Marten to enable that? Do you have any vision for how you'd want to use that with Marten?

**Comment by mdissel** [comment]
Just like in RavenDb ;).. But for a start we could add some extensions methods like SoftDeletes is implemented... It's basically the same, if the entity can be secured (configurable via the schema) add an extra query to filter the entities based on acl. 
And a lot of other parts of course like users/roles, usercontext, impersonation, etc.

**Comment by jeremydmiller** [comment]
"Just like in RavenDb ;)" -- that's never the best answer in regards to Marten

**Comment by mdissel** [comment]
I remember from one of your blog post the words 'marten is a drop-in replacement for RavenDb', but much better of course ;) Part of RavenDb is also a user/role/permission model. 

I need something like this in my application, so I raised this issue. Not many reactions to my surprise. I will start working on this when we need it in our application..

ps. Keep up the good work. Highly appreciated!

**Comment by jeremydmiller** [comment]
We did say that at first, but we ditched that one fast because we kept finding more scenarios where we either didn't like the Raven API or just had different ideas about how something would work. I just think it's dangerous to say "do it exactly like Raven" is all.

The custom Linq filters are easy if you just depend on IMethodCallParser plugins. If you want something like `IQueryable<T>().MyCustomFunction().*****`, you'll have to dig into the Relinq customization a little bit for it to work in compiled queries. It's not *that* bad. Look at `MartenExpressionParser.TransformFlyweight` and all the customizations it adds for examples.

**Comment by CoreyKaylor** [comment]
Any security layer would have to just be sugar to translate to PG security itself otherwise there isn't much of a point to do it at all.

How would you secure the documents with PG itself? It's much easier to work backwards from that as a first step.

**Comment by jeremydmiller** [comment]
I'm going to close this one. I don't see us doing this beyond the GRANT support we've added for DdlRules. This can be handled outside of Marten as it is.
