### ISSUE TITLE
More E2E tests

### ISSUE THREAD

**Issue by zagyar** [JasperFx/marten#412]
Hello,
I was trying to use new Marten 0.9.5+ and found unexpected behaviour, pelase help me to move this forward and identify if this is a bug or expected behaviour.

Here are the code: https://github.com/zagyar/marten/commit/d16e30b4ac4d3c70b99f3659ddbdc62229f318e4

I added three failing tests, below are the main points:

1) live_aggregate_equals_inlined_aggregate_without_hidden_contracts
Below objects from are not equal in some cases:
var liveAggregate = session.Events.AggregateStream<QuestParty>(questId);
var inlinedAggregate = session.Load<QuestParty>(questId);

2) open_persisted_stream_in_new_store_with_same_settings
Show how live aggregate fail with NPE if we try to use in in new DocumentStore (it fail if stream exists).

3) query_before_saving - if we do session.Events.Query<QuestParty>() before session.SaveChanges() second will fail with "Specified method is not supported."

**Comment by jeremydmiller** [comment]
@zagyar I've been out of town, but I'm back now and I'll look through your tests tomorrow morning.

**Comment by jeremydmiller** [comment]
@zagyar,

So what I see so far is:

* Doing the live aggregation, it isn't assigning the Id of the stream to the aggregate. That's an oversight on my part, and easily correctible.

* In the `query_before_saving` test, it's failing because of this line of code:

```
var parties = session.Events.Query<QuestParty>().ToArray();`
```

If you change that to:

```
var parties = session.Query<QuestParty>().ToArray();
```

You're back to the issue with the empty Guid id's on the live aggregation. 

Aggregate documents are just documents according to Marten. The syntax for session.Events.Query<T>() is **only** meant to be used on the raw event data and not on aggregates. Not sure how we'll solve the usability issue here. Better exception message or better Xml comments I suppose.

**Comment by jeremydmiller** [comment]
@zagyar For the NRE problem in `open_persisted_stream_in_new_store_with_same_settings`, you now get this exception:

```
Marten.Events.UnknownEventTypeException : Unknown event type name alias 'quest_started.' You may need to register this event type through StoreOptions.Events.AddEventType(type)
```

One way or another, Marten needs to "know" what the event type names are before loading them like that. It's a usability problem we haven't sorted out yet.

**Comment by jeremydmiller** [comment]
See https://github.com/JasperFx/marten/commit/78ad0470fd914a28b1a073126aabc6c8a96244d7 for more details. If you don't mind, I'd like to close this one, but replace it with a new issue about the EventTypeName usability.

**Comment by jeremydmiller** [comment]
See https://github.com/JasperFx/marten/issues/419 for the usability improvement ideas that tripped you up here.

**Comment by zagyar** [comment]
Great solution and feedback, thank you!
