### ISSUE TITLE
Update Documentation for 1.0

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#429]
- [x] Redo docs on identity management, new custom identifiers, private Id's, `[Identity]`
- [x] Using Jil
- [x] Using your own Newtonsoft version
- [x] Metadata columns, how to retrieve the metadata for a document, how to retrieve the version for a document
- [x] Schema management, WritePatch(), new Assert() method, build everything upfront, rollback scripts
- [x] Rip out discussion of Roslyn and say that we replaced it
- [x] Bulk Insert with the BulkInsertMode
- [x] Pagination, Stats(), inside Compiled Query too
- [x] Event Store changes, new sequence id, when information is available on event streams after SaveChanges(), QueryRawEventDataOnly()
- [x] Removed support for 9.4
- [x] Optimistic versioning, reading the exceptions, registering the version yourself, finding the version
- [x] Javascript Transformations, using, loading
- [x] Javascript transformations with Select(), using TransformToJson()
- [x] Computed indexes and the new Duplicate() field
- [x] Patching API
- [x] Soft Deletes
- [ ] Arbitrary operations in the Transaction?
- [x] Changed syntax of FindJson() methods
- [x] Make sure there's an Async example for everything 
- [x] Default Guid id is now CombGuid

**Comment by JohannesRudolph** [comment]
Fantastic project. I'm a long time user of RavenDB and thus can relate to some of the pain points. This time around though I'm primarily interested in Marten because I need ACID and a few relational bits as well (document + relational model). 

I think there's an async sample missing here: http://jasperfx.github.io/marten/documentation/documents/basics/loading/

Keep up the good work!
