### ISSUE TITLE
Fix Baseline dependency Nuget package

### ISSUE THREAD

**Issue by kamranayub** [JasperFx/marten#458]
Marten 0.9.12.563

Installing this package version will fail for users when using .NET 4.6.

```
Unable to find a version of 'Baseline' that is compatible with 'Marten 0.9.12.563 constraint: Baseline (>= 1.0.0-alpha-32)'.
```

Appears to only work if I force-install Baseline first, then install Marten after--I think the prerelease Baseline package is missing framework targets in the nuspec.

Couple other issues I had when installing on a 4.6 project:

- Missing System.Data.Common dependency
- Missing System.Reflection.TypeExtensions dependency

I could not reproduce initializing a database connection in raw npgsql, I could only repro with vanilla Marten install.

**Comment by CoreyKaylor** [comment]
The latest version targets Baseline 1.1.0 and should fix this issue. Feel free to re-open if that's not the case. Some of this is actually split across several projects though. System.Data.Common would actually be a dependency of Npgsql, TypeExtensions is a dependency of Baseline, etc. If they still aren't coming down, it's likely a problem with the nuget client and not our versions because I can see on nuget.org that they are specified as dependencies.
