### ISSUE TITLE
Flag to replace DROP TABLE with IF NOT EXISTS check when creating DDLs

### ISSUE THREAD

**Issue by scottoffen** [JasperFx/marten#470]
Currently, when creating a DDL (e.g. using `WriteDDL()`) adds statements to drop tables before recreating the tables. If the DDL scripts were to be used to upgrade and existing database, data would be lost. It would be prefered if there was a flag to disable this behavior and replace CREATE statements with CREATE IF NOT EXISTS statements.

**Comment by bradyclifford** [comment]
I could see the argument against this that one should use the WritePatch() method instead to upgrade existing database.  The problem is the WritePatch method also includes DROP on its tables.  Replacing the DROP and adding a IF NOT EXISTS, THEN CREATE would help ease the concern from our database team; for both the WritePatch() and WriteDDL() methods.

This of course is a want, not a need at this point.

**Comment by jeremydmiller** [comment]
@scottoffen @bradyclifford The WriteDDL was meant for documentation purposes. `WritePatch()` was built specifically for making change scripts. I'm not opposed to doing this, but I don't see it as necessary to be honest.

**Comment by bradyclifford** [comment]
I would agree that the WriteDDL doesn't need this feature. However, we are being asked by our database team to remove the DROP and add a IF NOT EXISTS for DDL scripts generated by the `WritePatch()` method.  We will be using our `Dev` database as a source of truth that the WritePatch() will point to to create the delta.

**Comment by jeremydmiller** [comment]
@bradyclifford The only time WritePatch() would do a `DROP TABLE` is if the document table is all new, but regardless, it's not a huge deal. I'd prefer not to have this in WriteDDL at all.
