### ISSUE TITLE
Bug in Linq query parsing

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#643]
If the Linq query contains something *not* related to the delegate that evaluates to true (that is, not a property of the class being queried), the rest of the query is not used. To make a bit more sense, take this (contrived for simplicity) lambda as an example:

`session.Query<Car>().Where(x => x.LicensePlate == "MART3N" && true);`

This gets parsed to the following query:

`select d.data, d.id, d.mt_version from public.mt_doc_car as d where true`

**Comment by jeremydmiller** [comment]
Something like this has come up before. My question then and now is "why would you do that?"

At most, I think we'd have Marten throw an exception if it can detect that.

**Comment by cocowalla** [comment]
Sorry, I simplified the example to make it super clear what the problem was - but looking again, I've perhaps over done it :)

The issue really is for conditions that are evaluated at runtime.

As a more concrete example, while creating or editing `Widget`s, I want to check if the specified name already exists (when adding) - unless it's the same `Widget` being edited (when editing). I'd use a Linq query something like this:

`var isDuplicate = session.Any(x => x.Name == widget && (isAdd || !x.Id == widget.Id))`

Where `widget` is the `Widget` being added or edited, and `isAdd` denotes whether we are adding or editing a `Widget`.

**Comment by jeremydmiller** [comment]
@cocowalla Again, I think the only "fix" would be to have Marten to throw an exception if it detects a literal "true." I can't imagine that any Linq query provider would truly support that scenario.

**Comment by cocowalla** [comment]
When you say 'literal true', do you mean an expression that evaluates to true at runtime, or simply 'true' as in my first example?

I'm pretty sure this works with Entity Framework, and I believe I've used it with NHibernate in the past too.

**Comment by jeremydmiller** [comment]
I'm saying that the Linq expression is nothing but a boolean value when it's handed in by Relinq -- same as EF and I have no idea about NH.

Dude, that's a crazy amount of work to parse each and every possible combination of true/false and something else within the Linq parsing. You'd have to first look for that possibility first, then abort the normal Linq visitor stuff.

I guess what I'm saying is that there's very little chance that I'm going to be willing to address this because I don't feel like it's a valid use case. Simply do an if/then in your code to use the correct query and you're good to go. More code, but I bet that code would be easier to understand and follow anyway.
