### ISSUE TITLE
Support using Postgresql Sequence's for int and long id's

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#66]
HiLo assignment is working, so this is probably a low priority. As in, not gonna do it until someone else does the PR or asks for it;)

**Comment by phillip-haydon** [comment]
I think this should be closed and not worried about. 

It will add way too much complexity because you will have to check the identity mapping to know if you can support batch inserts or not since you will need to roundtrip to the database to get the Ids after insert. 

Which also means performance issues. 

I think if someone is wanting to use sequence inserts they shouldn't be using Marten. (my 2c)

**Comment by jeremydmiller** [comment]
Heh, I'm good with that. Closing.

**Comment by jeffdoolittle** [comment]
Request to reconsider opening this back up. Not sure sequences are a requirement for us or anyone else, but if they were enabled, Marten could just disallow bulk loads to such documents. Just a thought.
