### ISSUE TITLE
Query<BaseT>.OfType<SubT> throws exception

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#712]
Hello. I have two classes.
```
public class BaseClass { }
public class ClassA { }
```
This linq request works:
`var result = session.Query<BaseClass>().OfType<BaseClass>().ToList();`
But another request 
`var result = session.Query<BaseClass>().OfType<ClassA>().ToList();`
throws exception:

> Exception thrown: 'System.NullReferenceException' in Marten.dll
> StackTrace:
> Marten.Linq.Model.LinqQuery`1.ConfigureCommand(NpgsqlCommand command, Int32 limit)> 

Maybe I do somethins wrong? I need session.Query<> from BaseClass and OfType<> by nested classes.

**Comment by jeremydmiller** [comment]
What are you trying to do? If you're using the hierarchical storage, you can query directly for ClassA.

**Comment by KopIlya** [comment]
I'm making an interface that isolates the storage system. I send out the QueryableObject
`session.Query<BaseClass>()`
I do not know what type of query is required in linq requests. So I give the query from the base type.

**Comment by jeremydmiller** [comment]
@KopIlya Have you seen this? http://jasperfx.github.io/marten/documentation/documents/advanced/hierarchies/

That should let you query directly against either `BaseClass` or `ClassA` even though it's all stored in the same table. 

Regardless, I think it'd work if you did `ToList().OfType<T>` instead of the order above

**Comment by KopIlya** [comment]
Yes, I saw. It did not help me. So I created this issue. I can not build a query directly on a subtype, because I send QueryableObject out and I do not know what kind will be a linq request.
The option ToList().OfType <T> this is not effective. Objects of the basic type can be many and objects of subtype - a little. But they all rise in memory. It is a bad idea.

**Comment by jeremydmiller** [comment]
@KopIlya What does your `QueryableObject` look like? Instead of trying to do `Query<BaseClass>().OfType<ClassA>()`, could you make the QueryableObject-to-Linq translation smart enough to go straight to `Query<ClassA>()`? I can help with the generic type trickery if you want.

Otherwise, if you wanna use a combination of the Hierarchical storage and do a pull request for supporting the `OfType` operator, I can help you with that as well.

**Comment by KopIlya** [comment]
I could not make my `QueryableObject` understand what subtype is requested in the linq request. I downloaded the source code to try to add support for the `OfType` operator. But I have two questions.
1. In `SampleConsoleApp` in creating `DocumentStore` I have exception `System.InvalidOperationException: 'Could not find embedded resource: Marten.Schema.SQL.mt_patching.js' 
in Marten.Schema.SchemaBuilder.ReadFromStream(String name, String databaseSchemaName)`
Do you have any idea how I can fix it?
2. About this topic, my code 
`var result = session.Query<BaseClass>().OfType<ClassA>().ToList();`
lead me to 
`Marten.Linq.Model.LinqQuery`1.ConfigureCommand(NpgsqlCommand command, Int32 limit)>`
For realize support the `OfType` operator I must look in this method `ConfigureCommand()`?
Please direct me.

Maybe this is not the right place for questions about starting SampleConsoleApp, I'm sorry.

**Comment by jeremydmiller** [comment]
@KopIlya Still wanna go back to this. If your code *can* call `OfType<ClassA>()`, why can't you just call `Query<ClassA>()` directly?

**Comment by KopIlya** [comment]
I was able to make call `Query<ClassA>()` directly.
Sorry for the time spent.
