### ISSUE TITLE
Multi-Property indexing support

### ISSUE THREAD

**Issue by phillip-haydon** [JasperFx/marten#733]
Implement support for multi-property indexing. 

Proposed API:

```csharp
    _.Schema
        .For<User>()
        .Index(x =>
        {
            x.AddColumn(prop => prop.FirstName);
            x.AddColumn(prop => prop.LastName);

            x.IndexName = "first_last_name_index";
        });
```

This can work along-side the existing index API for single property, however the existing api will call into the new api as they are both the same, except that the new api supports multiple properties.

**Comment by mariusin79** [comment]
Hi, just a tip, since we are conceptually doing this on my team already:

Class inheriting MartenRegistry:

            For<StreamOverviewViewModel>().Duplicate(vm => vm.UtcStartTime, configure: idx =>
            {
                idx.IndexName = "mt_idx_query_scheduledtorunondate";
                idx.Expression = "mt_deleted, utc_start_time, utc_end_time";
            });

            For<StreamOverviewViewModel>().Duplicate(vm => vm.UtcEndTime, configure: idx =>
            {
                idx.IndexName = "mt_idx_query_scheduledtorunondate";
                idx.Expression = "mt_deleted, utc_start_time, utc_end_time";
            });

Then in your patching tool of choice (we are using roundhouse https://github.com/chucknorris/roundhouse):

CREATE INDEX mt_idx_query_scheduledtorunondate ON fossmain.mt_doc_streamoverviewviewmodel (mt_deleted, utc_start_time, utc_end_time);
