### ISSUE TITLE
Store raw json

### ISSUE THREAD

**Issue by KopIlya** [JasperFx/marten#797]
Hello. The documentation has a description of how to download raw json. [http://jasperfx.github.io/marten/documentation/documents/querying/query_json/](http://jasperfx.github.io/marten/documentation/documents/querying/query_json/)
But I can not find how to save raw json.
If I try 
`session.Store(json);`
`session.StoreObjects(new []{json});`
the catch System.Reflection.TargetInvocationException.
How can save raw json?

**Comment by jeremydmiller** [comment]
There is no facility to load the raw json directly

**Comment by KopIlya** [comment]
I cab load raw json like there [ckick](http://jasperfx.github.io/marten/documentation/documents/querying/query_json/).
Do you mean no facility to STORE raw json? Will there be such a function in the future?

**Comment by jeremydmiller** [comment]
It's not something I'd honestly want to support. You'd have to recreate basically everything that normally happens when a document is loaded as far as metadata tables, duplicated fields, and id columns. There's nothing stopping you from using the generated upsert statements directly against the database though
