### ISSUE TITLE
Optimistic concurrency / metadata

### ISSUE THREAD

**Issue by ejsmith** [JasperFx/marten#825]
I'm trying to figure out how to make use of the optimistic concurrency feature in Marten. The way my app currently works is that I get a document that includes the document version and I pass that down to the client. The client can then make changes to the document and submit it back to the server. The server tries to apply the changes using the version that the changes were made against and fails if someone else made other changes. Here are some questions I have:

1. How can I have the version included in my queries without having to iterate over the documents and call MetadataFor which appears to do another SQL call per document?
2. Is it possible to have the version mapped onto the document so that I can have the version flow down to the client and back to the server with the version attached to it? Maybe we need some sort of `Meta<T>` that could wrap the documents and be returned. We could have an `IQueryable<T>` extension that transforms the result to return `Meta<T>`.
3. It appears that the use of a guid for the version is modeled after RavenDb, but they had much different needs with it being used as an etag and a mechanism to help with eventual consistency issues. It would be nice if the document version was a simple incrementing long. It doesn't seem like it would be too big of a change to convert it from a guid to an incrementing long, but it would be a big breaking change that would require a data migration for existing apps so that is a pretty big deal. Figured I would ask anyway just to see if you would be interested in a change like this. I personally feel like its a change worth making especially since you are already in the middle of doing a set of breaking changes for 2.0.
4. I'm not of fan of how the MetadataFor method moved to session.Tennant.MetadataFor in 2.0. I can see how that makes sense for documents that use tenancy, but seems weird when you aren't using tenancy. IMO, the original home of Advanced made more sense. Couldn't it just have tenant id overloads like the session.Store method does?

**Comment by petersondrew** [comment]
I am running into a similar situation myself where I need to make two queries to fetch the document version. In order to minimize the pain I do not return the document versions when returning documents in bulk. Instead, when the client wishes to edit a document they fetch it individually along with the current version. 

I like your thoughts on some kind of `Meta<T>` wrapper, that would keep document models the cleanest. If the impact on the API is too great, we could also possibly mark our documents with an `IHaveMetadata` interface so that Marten would know to attempt to set the Version property on that document if it exists (with or without the use of attributes).

Regarding the tenant vs advanced thing, hopefully any work for items for items 1 or 2 would remove that pain for you. I am using tenants so I can't empathize as much on that point ;-).

**Comment by petersondrew** [comment]
I'd be willing to put some work in on a PR for this if we can talk through it enough, either here or on gitter.

**Comment by ejsmith** [comment]
@petersondrew agreed. I think the `Meta<T>` idea could work very well and maybe there could be other strategies that would do something with the metadata like what you suggested with the documents implementing `IHaveMetadata`

**Comment by jeremydmiller** [comment]
"It doesn't seem like it would be too big of a change to convert it from a guid to an incrementing long" -- that would break every single existing Marten database, and it would be quite a non-trivial change to the underlying code. I'd buy this as an opt in, but not as the default approach.

@petersondrew I'm good w/ the Meta<T> wrapper idea, and that shouldn't be that crazy to do as an extension to the Linq support. I'd rather do that than use the `IHaveMetadata` approach.

The metadata thing on tenant vs advanced is a bit problematic. At a minimum, it has to stay on `IDocumentSession` so that you're using the current tenant for when we start doing a database or schema per tenant. Happy to take a PR for that if you want;)

**Comment by ejsmith** [comment]
Awesome! Thank you.

**Comment by petersondrew** [comment]
:+1:
