### ISSUE TITLE
Optimize the First() & Last() mechanics by limiting the results

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/marten#89]
Instead of doing a complete fetch and then grabbing the first or last in that array, let's try to make the DB query only return the correct value

**Comment by ekulakov** [comment]
@jeremydmiller If someone need `Last()` then he should use `OrderByDescending()` + `First()` instead of `Last()`.

From PostgreSQL docs: When using LIMIT, it is important to use an ORDER BY clause that constrains the result rows into a unique order. Otherwise you will get an unpredictable subset of the query's rows. You may be asking for the tenth through twentieth rows, but tenth through twentieth in what ordering? The ordering is unknown, unless you specified ORDER BY. [Source](http://www.postgresql.org/docs/8.1/static/queries-limit.html)

BTW EF is not supported `Last()` too.

**Comment by jeremydmiller** [comment]
@ekulakov That's a pretty easy argument to accept. First() only, and Last() will throw an exception telling you to order by descending, then first.

**Comment by jeremydmiller** [comment]
This should be marked as "closed" by commit https://github.com/JasperFx/marten/commit/ba0d06f4d5f1cbeed294ef59d8e1e6929969b1b6
