### ISSUE TITLE
Multiple document versions

### ISSUE THREAD

**Issue by cocowalla** [JasperFx/marten#897]
What I want to do is maintain historical versions for a document, such that only the latest is the 'live' version - previous versions are essentially soft deleted.

The way I see to do this with Marten is to configure `SoftDeleted` for the type, then when I want to create a new version:

1. Load and modify the existing version as required
2. Change the `Id` property
3. `Store` the updated version
4. `Delete` the previous version using its ID e..g `session.Delete<MyType>(previousId)`

I would need to use optimistic concurrency to ensure we couldn't end up with 2 'live' versions. I'd also need to add an extra `Guid` property to my type, which would *not* change across versions, and would provide a means for all versions of a document to be 'linked' together.

So, I have a couple of questions relating to this:

- Can Marten do composite primary keys? I'm not a fan of them in general, but they would seem to provide an alternative solution in this scenario
- Do you see any issues with the approach outlined above, and is there some other way to achieve it?

**Comment by jeremydmiller** [comment]
@cocowalla,

We *technically* have the ability to do composite keys as a side effect of the multi-tenancy, but I'd really not recommend that. If you want to do this, I'd strongly recommend keeping a shadow "archive" table where you keep historical versions just to keep the main table as clean as possible. 

Honestly, is this a place where event sourcing would be more appropriate rather than using the full document versioning?

**Comment by cocowalla** [comment]
Fair enough, I do try to avoid composite keys where possible.

I only need to do this for one type of document, and there will never be more than 50 or so documents in the table, so I'm not too concerned about 'dirtiness' - I think I'll just stick with the approach I described in my first post.
